import { Injectable } from '@nestjs/common';
import { BaseAgent } from './base.agent';
import { AgentRole, ModelRouteConfig } from '@ai-corp/shared-types';
import { MemoryService } from '../memory/memory.service';
import { LLMProviderFactory } from '../llm/llm-provider.factory';
import { ToolRegistry } from '../tools/tool.registry';
import { SandboxExecutor } from '../tools/sandbox.executor';
import { ApiUsageService } from '../llm/api-usage.service';
import { AppWebSocketGateway } from '../websocket/websocket.gateway';

@Injectable()
export class QaAgent extends BaseAgent {
  constructor(
    memoryService: MemoryService,
    llmFactory: LLMProviderFactory,
    toolRegistry: ToolRegistry,
    sandboxExecutor: SandboxExecutor,
    apiUsageService: ApiUsageService,
    websocketGateway: AppWebSocketGateway
  ) {
    const systemPrompt = `You are the QA Engineer. Your objective is to review code, run tests, and ensure software quality.
You are reviewing code that was generated by an AI developer. The code may not be perfect but should be reasonable.
Focus on: Does the code exist? Is it a real implementation (not a placeholder)? Does it address the task?`;
    const modelConfig: ModelRouteConfig = { provider: 'opencode', model: 'openrouter/nvidia/nemotron-3-super-120b-a12b:free', fallbackProvider: 'opencode' };
    super(AgentRole.QA, systemPrompt, modelConfig, memoryService, llmFactory, toolRegistry, sandboxExecutor, apiUsageService, websocketGateway);
  }

  async think(context: any): Promise<any> {
    this.logger.debug('QA thinking...');
    this.emitThinking(context.projectId, "Planning testing strategy for the provided code.");

    const memories = await this.loadMemory('testing_patterns', JSON.stringify(context));
    return { thought: "Planning testing strategy for the provided code.", memories };
  }

  async act(context: any): Promise<any> {
    this.logger.debug('QA acting...');
    const memories = context.memories || [];
    const memoryContext = memories.length > 0
      ? `\n\nRelevant testing patterns:\n${memories.map((m: any) => m.content).join('\n')}`
      : '';

    const code = context.code || '';
    const hasCode = code.length > 10 && !code.includes('No code provided');

    const prompt = `You are a QA engineer reviewing code from an AI developer.
${memoryContext}
Code to review:
${hasCode ? code : 'No code was provided by the developer.'}

Rules for your verdict:
- If real implementation code exists (even if imperfect), reply: VERDICT: PASS
- Only reply VERDICT: FAIL if there is absolutely NO code or the code is a pure placeholder (like "echo hello" or just comments)
- Remember: imperfect code is still code. Only reject empty/placeholder responses.

Reply with EXACTLY one of these on the last line:
VERDICT: PASS
VERDICT: FAIL`;

    const result = await this.callLLM({
      messages: [{ role: 'user', content: prompt }],
      maxTokens: 800
    }, context.projectId);

    await this.saveMemory('testing_patterns', `Reviewed code for task: ${context.taskId || 'unknown'}`, 5, context.projectId);

    this.emitAction(context.projectId, context.taskId || 'none', 'review', 'llm', { codeLength: code.length });

    const output = result.content || '';
    const outputUpper = output.toUpperCase();

    // Check for explicit failure - multiple patterns
    const explicitlyFailed = outputUpper.includes('VERDICT: FAIL')
      || outputUpper.includes('VERDICT:FAIL')
      || outputUpper.includes('VERDICT:\\s*FAIL');

    // Check for explicit pass
    const explicitlyPassed = outputUpper.includes('VERDICT: PASS')
      || outputUpper.includes('VERDICT:PASS');

    // Default: approve if code exists, reject only if explicitly failed
    let approved: boolean;
    if (explicitlyFailed) {
      approved = false;
    } else if (explicitlyPassed) {
      approved = true;
    } else {
      // No clear verdict - approve if code exists
      approved = hasCode;
    }

    this.logger.log(`QA review result: ${approved ? 'APPROVED' : 'REJECTED'} (explicitlyFailed=${explicitlyFailed}, explicitlyPassed=${explicitlyPassed}, hasCode=${hasCode})`);

    return { 
      action: 'review', 
      output,
      qa_approved: approved,
      edgeCondition: approved ? 'onSuccess' : 'onFail'
    };
  }
}
